#:kivy 2.0.0
#:import kivy kivy
#:import win kivy.core.window

# Standard values for use throughout the file
#:set std_padding 10
#:set line_height 30

<Root>:
    orientation: 'vertical'

    # Make the applicatin's background white rather than black
    # background_color: 1, 1, 1, 1
    # canvas.before:
    #     Color:
    #         rgba: root.background_color
    #     Rectangle:
    #         size: self.size
    #         pos: self.pos

    # The filename is displayed at the top of the application
    Label:
        text: 'Image path: [b]' + image.source + '[/b]'
        # color: 0,0,0,1
        markup: True
        size_hint: 1, None
        text_size: self.size
        halign: 'left'
        valign: 'middle'
        padding_x: std_padding
        height: line_height

    StackLayout:
        orientation: 'lr-tb'
        size_hint: 1, None
        padding: std_padding, 0, std_padding, 0
        spacing: std_padding, 0
        height: line_height

        Label:
            text: "Is image tagged with an animal: "
            size_hint: None, None
            size: self.texture_size
            padding_y: 5

        CheckBox:
            id: isActive
            size_hint: None, None
            width: line_height # Weird, but easy
            height: line_height

    AsyncImage:
        id: image
        source: 'D:/data/NRSI/2140_Turtle Nesting-Wildlife-Cameras-2019/Camera-5/2019_07_10/RCNX0090.JPG'
        # size_hint: 1,1
