#:kivy 2.0.0
#:import kivy kivy
#:import win kivy.core.window

# Standard values for use throughout the file
#:set std_padding 10
#:set line_height 30

<Root>:
    orientation: 'vertical'

    # Binding "global" variable names for the IDs in main.py
    imageWidget: imageWidget
    imageNumberWidget: imageNumberWidget
    isActiveWidget: isActiveWidget

    # The filename is displayed at the top of the application
    StackLayout:
        orientation: 'lr-tb'
        size_hint: 1, None
        padding: std_padding, 0, std_padding, 0
        spacing: std_padding, 0
        height: line_height

        Label:
            text: 'Image path:'
            size_hint: None, None
            size: self.texture_size
            padding_y: 5

        TextInput:
            id: imageNumberWidget
            on_text_validate: root.onJumpToImage
            text: "------"
            multiline: False
            size_hint: None, 1
            # size: self.texture_size
            padding_y: 5

        Label:
            text: imageWidget.source
            size_hint: None, None
            size: self.texture_size
            padding_y: 5


    StackLayout:
        orientation: 'lr-tb'
        size_hint: 1, None
        padding: std_padding, 0, std_padding, 0
        spacing: std_padding, 0
        height: line_height

        Label:
            text: "Is image tagged with an animal: "
            size_hint: None, None
            size: self.texture_size
            padding_y: 5

        CheckBox:
            id: isActiveWidget
            size_hint: None, None
            width: line_height # Weird, but easy
            height: line_height

    AsyncImage:
        id: imageWidget
        source: '--None--'
        # size_hint: 1,1
